server:
  port: 8761
 
spring:
  application:
    name: ap-eureka-server
  security:
    user:
      name: admin
      password: admin
     
eureka:
  instances:
    hostname: localhost
    non-secure-port: ${server.port}
    instanceId: client-${random.uuid}
    prefer-ip-address: true
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka